# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c9d2a21033679685c095d8f9d7f3c738180b263d233fe909a116d6289d318701b67dcc0199eb4253764dec4721f0dba188569d5610c8167267bb01173b2330b

test:
  secret_key_base: 2663ae46b150eb70a998fb57e8661d138ac996cd25011eee6bf7338671e9bd53a2334b45995c16a38e007c43c0c74718b9cd4081bf283e6c1650dbbcd6c2413d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
